"""create raw tables

Revision ID: 84a9ab83bcf4
Revises: 
Create Date: 2026-05-15 14:48:52.727056
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84a9ab83bcf4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offline_test',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('coupon_id', sa.String(length=64), nullable=True),
    sa.Column('discount_rate', sa.String(length=64), nullable=True),
    sa.Column('distance', sa.String(length=16), nullable=True),
    sa.Column('date_received', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='raw'
    )
    op.create_index(op.f('ix_raw_offline_test_merchant_id'), 'offline_test', ['merchant_id'], unique=False, schema='raw')
    op.create_index(op.f('ix_raw_offline_test_user_id'), 'offline_test', ['user_id'], unique=False, schema='raw')
    op.create_table('offline_train',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('coupon_id', sa.String(length=64), nullable=True),
    sa.Column('discount_rate', sa.String(length=64), nullable=True),
    sa.Column('distance', sa.String(length=16), nullable=True),
    sa.Column('date_received', sa.String(length=16), nullable=True),
    sa.Column('date', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='raw'
    )
    op.create_index(op.f('ix_raw_offline_train_merchant_id'), 'offline_train', ['merchant_id'], unique=False, schema='raw')
    op.create_index(op.f('ix_raw_offline_train_user_id'), 'offline_train', ['user_id'], unique=False, schema='raw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_offline_train_user_id'), table_name='offline_train', schema='raw')
    op.drop_index(op.f('ix_raw_offline_train_merchant_id'), table_name='offline_train', schema='raw')
    op.drop_table('offline_train', schema='raw')
    op.drop_index(op.f('ix_raw_offline_test_user_id'), table_name='offline_test', schema='raw')
    op.drop_index(op.f('ix_raw_offline_test_merchant_id'), table_name='offline_test', schema='raw')
    op.drop_table('offline_test', schema='raw')
    # ### end Alembic commands ###
