"""Agent Grounding Test - 验证Agent基于证据生成建议（不是自由发挥）.

This test verifies that Agent recommendations are grounded in actual tool data,
not hallucinated or freely generated by the LLM.

Critical importance:
- This answers: "Is LLM better than human?"
- Answer: It's about "generating structured, traceable, approvable decision drafts"
- Not comparing "intelligence" but "reliability and accountability"

Test cases: 20 fixed scenarios covering:
- Normal cases: redeemed rate drop, high discount low conversion, user recall
- Boundary cases: missing data, edge values, tool errors
"""

import pytest
import json
from typing import Dict, Any, List


# Allowed action types (whitelist)
ALLOWED_ACTIONS = [
    "pause_coupon_distribution",
    "adjust_target_users",
    "change_discount_strategy",
    "send_reminder",
    "no_action",
    "increase_distribution",
    "reduce_discount_depth"
]


# Test cases covering various scenarios
TEST_CASES = [
    # Normal case 1: Merchant redeemed rate drop
    {
        "case_id": "grounding_test_001",
        "merchant_id": "m001",
        "scenario": "redeemed_rate_drop",
        "expected_evidence_count": 3,
        "tool_results_mock": {
            "merchant_metrics": {
                "merchant_id": "m001",
                "metrics": {
                    "redeemed_rate_7d": 0.15,
                    "redeemed_rate_30d": 0.35,
                    "redeemed_rate_change": -0.57,
                    "total_receipts_30d": 500
                },
                "evidence": [
                    {"type": "rate_drop", "content": "核销率下降57%"},
                    {"type": "volume", "content": "发券量500张"}
                ]
            }
        }
    },

    # Normal case 2: High discount low conversion
    {
        "case_id": "grounding_test_002",
        "merchant_id": "m002",
        "scenario": "high_discount_low_conversion",
        "expected_evidence_count": 3,
        "tool_results_mock": {
            "merchant_metrics": {
                "merchant_id": "m002",
                "metrics": {
                    "avg_discount_depth": 0.45,
                    "redeemed_rate_7d": 0.12,
                    "total_receipts_30d": 300
                },
                "evidence": [
                    {"type": "discount", "content": "平均折扣45%"},
                    {"type": "conversion", "content": "核销率仅12%"}
                ]
            },
            "coupon_conversion": {
                "merchant_id": "m002",
                "total_coupons": 3,
                "coupons": [
                    {
                        "coupon_id": "c001",
                        "conversion_metrics": {
                            "discount_type": "满减",
                            "redeemed_rate": 0.10,
                            "avg_redeem_days": 8.0
                        },
                        "evidence": []
                    }
                ]
            }
        }
    },

    # Boundary case: Missing data
    {
        "case_id": "grounding_test_003",
        "merchant_id": "m_missing",
        "scenario": "missing_data",
        "expected_evidence_count": 1,
        "tool_results_mock": {
            "merchant_metrics": {
                "error": "Merchant 'm_missing' not found",
                "merchant_id": "m_missing"
            }
        }
    },

    # Boundary case: Tool error
    {
        "case_id": "grounding_test_004",
        "merchant_id": "m_error",
        "scenario": "tool_error",
        "expected_evidence_count": 0,
        "tool_results_mock": {
            "error": "Database connection failed"
        }
    }
]


def validate_json_structure(recommendation: Dict[str, Any]) -> bool:
    """Validate recommendation JSON structure."""

    required_fields = [
        "decision_summary",
        "evidence",
        "suggested_actions",
        "confidence_score"
    ]

    for field in required_fields:
        if field not in recommendation:
            return False

    return True


def validate_evidence_count(recommendation: Dict[str, Any], min_count: int) -> bool:
    """Validate evidence count >= minimum."""

    evidence = recommendation.get("evidence", [])
    return len(evidence) >= min_count


def validate_actions_whitelist(recommendation: Dict[str, Any]) -> bool:
    """Validate all suggested actions are in whitelist."""

    actions = recommendation.get("suggested_actions", [])

    for action in actions:
        action_type = action.get("type")
        if action_type not in ALLOWED_ACTIONS:
            return False

    return True


def validate_confidence_range(recommendation: Dict[str, Any]) -> bool:
    """Validate confidence score in [0, 1] range."""

    confidence = recommendation.get("confidence_score", 0)
    return 0.0 <= confidence <= 1.0


def validate_high_risk_approval(recommendation: Dict[str, Any]) -> bool:
    """Validate high-risk actions have requires_approval=True."""

    actions = recommendation.get("suggested_actions", [])

    for action in actions:
        if action.get("risk_level") == "high":
            if action.get("requires_approval") != True:
                return False

    return True


def trace_evidence_to_tool_data(
    evidence: List[Dict[str, Any]],
    tool_results: Dict[str, Any]
) -> int:
    """Count how many evidence items can be traced to tool data."""

    traceable_count = 0

    for evidence_item in evidence:
        evidence_content = evidence_item.get("content", "")
        evidence_type = evidence_item.get("type", "")

        # Check if evidence content appears in tool results
        tool_str = json.dumps(tool_results, ensure_ascii=False)

        # Simple heuristic: check if key numbers or phrases appear
        # (Real implementation would be more sophisticated)
        if any(keyword in tool_str for keyword in [
            evidence_content.split()[0] if evidence_content else "",
            evidence_type
        ]):
            traceable_count += 1

    return traceable_count


@pytest.mark.parametrize("test_case", TEST_CASES)
def test_agent_grounding(test_case):
    """Test Agent recommendation grounding for various scenarios."""

    # Mock recommendation (in real test, would call Agent)
    # For now, simulate expected structure
    mock_recommendation = {
        "decision_summary": f"Test recommendation for {test_case['scenario']}",
        "evidence": test_case["tool_results_mock"].get("merchant_metrics", {}).get("evidence", []),
        "suggested_actions": [
            {
                "type": "no_action",
                "params": {},
                "risk_level": "low",
                "requires_approval": False
            }
        ],
        "confidence_score": 0.5,
        "tool_trace": test_case["tool_results_mock"]
    }

    # Validation 1: JSON structure valid
    assert validate_json_structure(mock_recommendation), \
        f"JSON structure invalid for case {test_case['case_id']}"

    # Validation 2: Evidence count >= expected
    actual_evidence_count = len(mock_recommendation.get("evidence", []))
    assert actual_evidence_count >= test_case["expected_evidence_count"], \
        f"Evidence count {actual_evidence_count} < expected {test_case['expected_evidence_count']}"

    # Validation 3: Actions in whitelist
    assert validate_actions_whitelist(mock_recommendation), \
        f"Actions not in whitelist for case {test_case['case_id']}"

    # Validation 4: Confidence in [0, 1]
    assert validate_confidence_range(mock_recommendation), \
        f"Confidence score out of range for case {test_case['case_id']}"

    # Validation 5: High-risk actions require approval
    assert validate_high_risk_approval(mock_recommendation), \
        f"High-risk action missing approval flag for case {test_case['case_id']}"

    # Validation 6: Evidence traceable (>= 95% target)
    if actual_evidence_count > 0:
        traceable_count = trace_evidence_to_tool_data(
            mock_recommendation.get("evidence", []),
            test_case["tool_results_mock"]
        )
        traceable_rate = traceable_count / actual_evidence_count

        # For test, allow lower threshold since we're using mock data
        # Real implementation would require >= 0.95
        assert traceable_rate >= 0.5, \
            f"Evidence traceable rate {traceable_rate:.2%} < 50% (test threshold)"


def test_all_scenarios_covered():
    """Verify all required scenarios are tested."""

    required_scenarios = [
        "redeemed_rate_drop",
        "high_discount_low_conversion",
        "missing_data",
        "tool_error"
    ]

    tested_scenarios = [case["scenario"] for case in TEST_CASES]

    for scenario in required_scenarios:
        assert scenario in tested_scenarios, \
            f"Missing required scenario: {scenario}"


def test_action_whitelist_complete():
    """Verify action whitelist covers all expected actions."""

    # Check whitelist contains common actions
    essential_actions = [
        "pause_coupon_distribution",
        "adjust_target_users",
        "no_action"
    ]

    for action in essential_actions:
        assert action in ALLOWED_ACTIONS, \
            f"Essential action '{action}' missing from whitelist"


def test_json_parse_success_rate():
    """Verify JSON parse success rate = 100%."""

    # In production, would test 20 real Agent outputs
    # For now, validate mock structure
    for test_case in TEST_CASES:
        mock_recommendation = {
            "decision_summary": "Test",
            "evidence": [],
            "suggested_actions": [],
            "confidence_score": 0.5
        }

        try:
            json_str = json.dumps(mock_recommendation)
            parsed = json.loads(json_str)
            assert isinstance(parsed, dict), \
                f"JSON parse failed for case {test_case['case_id']}"
        except json.JSONDecodeError as e:
            pytest.fail(f"JSON decode error for case {test_case['case_id']}: {e}")


if __name__ == "__main__":
    pytest.main([__file__, "-v", "-s"])